#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Husky checks on commit'

# Check Prettier 
yarn check:format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint 
npm run check:lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check typescript 
npm run check:types ||
(
    echo 'Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo 'All checks passed, committing..'
